spring:
  kafka:
    consumer:
      group-id: rm_email_consumer
      properties:
        spring:
          json:
            trusted:
              packages: com.referminds.userservice.entity
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
      properties.spring.json.trusted.packages = co.orders.feedme.feed.domain
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: java.sharmarahul@gmail.com
    password: India!@#123
    properties.mail.smtp:
      auth: true
      starttls.enable: true
security:
  basic:
    enabled: false
