spring:
  kafka:
    consumer:
      group-id: rm_email_consumer
      properties:
        spring:
          json:
            trusted:
              packages: *
          value:
            default: com.referminds.userservice.entity.User
      value:
        deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener: 
      ack-mode: MANUAL
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
      
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rahultstacc@gmail.com
    password: Test@123
    properties.mail.smtp:
      auth: true
      starttls.enable: true
security:
  basic:
    enabled: false
